spring:
  application:
    name: orderlee-backend
  
  datasource:
    url: jdbc:h2:mem:orderlee
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:orderlee-secret-key-for-jwt-token-generation-2024}
  expiration: 86400000 # 24 hours

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY:sk_test_your_stripe_secret_key_here}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret_here}

logging:
  level:
    com.orderlee: DEBUG
    org.springframework.security: DEBUG